import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { CartProvider } from "./context/CartContext";
import Link from "next/link";
import { ShoppingCart } from "lucide-react";
import UserMenu from "./components/UserMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className="bg-gray-50 text-gray-900">
        <CartProvider>
          <nav className="flex justify-between items-center p-4 bg-white shadow">
            <h1 className="font-bold text-xl">Pastelería</h1>
            <div className="flex gap-4">
              <Link href="/" className="hover:underline">
                Inicio
              </Link>
              <Link href="/products" className="hover:underline">
                Tienda
              </Link>
              <Link href="/us" className="hover:underline">
                Nosotros
              </Link>
              <Link href="/events" className="hover:underline">
                Eventos
              </Link>
              <Link href="/cards" className="hover:underline">
                Cartas
              </Link>
              <Link
                href="/cart"
                className="relative hover:text-pink-600 transition"
                title="Ver carrito"
              >
                <ShoppingCart />
              </Link>
              <UserMenu />
            </div>
          </nav>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
